name: BankPlugin
version: 1.0
main: com.yourname.economyplugin.BankPlugin
api-version: 1.16
description: A bank plugin with general ledger functionality
commands:
  bank:
    description: Main command for bank operations
    usage: /<command> [subcommand] [args...]
    permission: bankplugin.use
permissions:
  bankplugin.use:
    description: Allows use of bank commands
    default: op